Add new scripts and files

diff --git a/delete-log b/delete-log
--- a/delete-log
+++ b/delete-log
@@ -3,7 +3,10 @@ USERID=$(id -u)
 R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
-N="\e[0m"/home/ec2-user/app-logs
+N="\e[0m"
+
+DAYS=${3:-14}
+
 
 LOGS_FOLDER="/var/log/shell-script"
 SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
@@ -12,18 +15,58 @@ LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log" # /var/log/shell-script/16-logs.log
 mkdir -p $LOGS_FOLDER
 echo "Script started executed at: $(date)" | tee -a $LOG_FILE
 
-SOURCE_DIR=/home/ec2-user/
+if [ $USERID -ne 0 ]; then
+    echo "ERROR:: Please run this script with root privelege"
+    exit 1 # failure is other than 0
+fi
+USAGE(){
+    echo -e "$R USAGE:: sudo sh 24-backup.sh <SOURCE_DIR> <DEST_DIR> <DAYS>[optional, default 14 days] $N"
+    exit 1
+}
+if [ $# -lt 2 ]; then
+    USAGE
+fi
+
+
+SOURCE_DIR=/home/ec2-user/app-logs
 
 if [ ! -d $SOURCE_DIR ]; then
     echo -e "ERROR:: $SOURCE_DIR does not exist"
     exit 1
 fi
 
-FILES_TO_DELETE=$(find $SOURCE_DIR -name "*.log" -type f )
+if [ ! -d $DEST_DIR ]; then
+    echo -e "ERROR:: $DEST_DIR does not exist"
+    exit 1
+fi
 
-while IFS= read -r filepath
-do
-    echo "Deleting the file: $filepath"
-    rm -rf $filepath
-    echo "Deleted the file: $filepath"
-done <<< $FILES_TO_DELETE
+FILES=$(find $SOURCE_DIR -name "*.log" -type f )
+
+if [ ! -z $FILES]; then
+echo "files found:$FILES"
+TIMESTAMP=$(date +%F-%H-%M)
+ZIP_FILE_NAME="$DEST_DIR/app-logs-$TIMESTAMP.zip"
+echo "zip file name:$ZIP_FILE_NAME"
+find $SOURCE_DIR -name "*.log" -type f -mtime +$DAYS | zip -@ -j "$ZIP_FILE_NAME"
+
+if [ -f $ZIP_FILE_NAME ];
+then
+    echo "Archival success"
+
+    while IFS= read -r filepath
+        do
+            echo "Deleting the file: $filepath"
+            rm -rf $filepath
+            echo "Deleted the file: $filepath"
+        done <<< $FILES
+
+else
+    echo "archeiving failure"
+exit 1
+fi
+else
+
+echo "no files to achieve....skipping"
+fi
+
+    
